name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-project:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    - name: Create Github release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ github.run_number }}
         release_name: Release ${{ github.run_number }}

    - name: Deploy to Backstage
      run: backstage-cli deploy localhost:3000
      env:
        BACKSTAGE_API_URL: ${{ secrets.BACKSTAGE_API_URL }}
        BACKSTAGE_API_TOKEN: ${{ secrets.BACKSTAGE_API_TOKEN }}

