name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout HomeTest
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt
   #   working-directory: ./your-python-app

    - name: Build and Test
      run: |
        pytest
        # Other build and test commands
    #  working-directory: ./your-python-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Backstage
      run: backstage-cli deploy localhost:3000
      env:
        BACKSTAGE_API_URL: ${{ secrets.BACKSTAGE_API_URL }}
        BACKSTAGE_API_TOKEN: ${{ secrets.BACKSTAGE_API_TOKEN }}

